version: '3.4'

services:
  mailbackend:
    container_name: mailbackend
    build:
      context: ./MailBackend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./env/secrets.env
      - ./env/postgres.env
    depends_on: 
      database:
        condition: service_healthy
    networks:
      - mreza

  database:
    image: postgres:latest
    container_name: database
    env_file:
      - ./env/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mreza
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d mejl_baza -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - mailbackend 
    networks:
      - mreza
  scraper:
    container_name: scraper 
    build:
      context: ./scraper
      dockerfile: Dockerfile 
    env_file:
      - ./env/scraper_config.env
      - ./env/secrets.env
    volumes:
      - ./scraper:/app
    depends_on:
      - mailbackend
    networks:
      - mreza

networks:
  mreza:
    driver: bridge

    
      


